### ISSUE TITLE
공용 UI

### ISSUE THREAD

**Issue by Roharui** [GiveUsMoney/FanFixiv#50]
**Tasks**

- [x]  상단 nav
    - [x]  로고를 클릭시 메인 화면으로 돌아옴
- [x]  성인물 표시 여부
    - [x]  비로그인 유저에게는 보이지 않음.
    - [x]  비성인 유저에게는 보이지 않음.
- [x]  프로필 아이콘
    - 로그인 했을때 나와야 하며 프로필 사진이 작게 표시되어야함.
    - 알림이 있을때 프로필 아이콘 우측 상단에 알림표시가 있어야함.
   - [x]  확장 기능란
        - 클릭 했을때 확장될 것.
        - [x]  내 프로필
            - [x]  클릭시 프로필 페이지로 이동
        - [x]  알림
            - [x]  알림이 있을시 우측에 확인하지 않은 알림의 개수를 뛰움
            - [x]  클릭시 알림창으로 이동
        - [x]  태그 목록
            - [x]  클릭시 태그 목록 페이지로 이동
        - [x]  번역 요청
            - [x]  클릭시 번역 요청 페이지로 이동
        - [x]  나의 좋아요
            - [x]  클릭시 좋아요 태그를 검색한 결과물 페이지로 이동
        - [x]  설정
            - [x]  내 프로필의 설정창으로 바로 이동
        - [x]  로그아웃
            - [x]  클릭시 정말 로그아웃 하시겠습니까? 문구를 뛰움
                - 로그아웃 / 취소 버튼이 있어야함

**레퍼런스**
- https://www.notion.so/a1d431ee708647449b63ca0fe4821b2f
